Merge changes in to support parsing bash scripts
binpash/pash pull request #737
Opened 2024-12-15 21:44 UTC by BolunThompson

Code written by @sethsabar. The tests pass with the changes from binpash/shasta#5 and binpash/libbash#1 (CI will fail until those are merged in).

2024-12-17 00:26 UTC, angelhof commented
I merged the depending PRs, but I suspect we also need to create a PyPI release of libbash correct?

2024-12-17 02:46 UTC, BolunThompson commented
You’re correct — thanks for catching that.

2024-12-21 00:42 UTC, angelhof commented
After merging libbash and pushing the repo to PyPI we should be able to continue working on this :)

2024-12-23 01:37 UTC, angelhof requested changes
Great job @BolunThompson and @sethsabar !! The only change that we need to do is to make sure that bash tests run in CI (not by modifying the yml file but rather the test scripts). In my opinion, it would be better to just modify all test files to run both with and without `--bash` for all tests (avoiding the control flow that exists currently), however I don't have a strong opinion on that.

2024-12-23 01:37 UTC, angelhof commented on evaluation/tests/test_evaluation_scripts.sh
> +                if [ "$test_mode" == "bash" ]; then
Do we need this here?

2024-12-23 01:37 UTC, angelhof commented on evaluation/tests/test_evaluation_scripts.sh
> +        if [ "$test_mode" == "bash" ]; then
I feel that we can just modify the file to run tests both with --bash and without (modifying the configurations array above).

2024-12-23 01:37 UTC, angelhof commented on scripts/run_tests_bash.sh
> +set -x e
We should run this script in CI!

2024-12-23 01:37 UTC, angelhof commented on evaluation/tests/interface_tests/run.sh
> +if [ "$#" -eq 0 ] || [ "$test_mode" = "bash" ]; then
I would really remove all these control flow checks and make sure that all tests always run both with and without --bash.

2025-01-04 07:03 UTC, BolunThompson commented
The current problem is that pash expands words in bash mode by calling `echo {arg}` for every arg, replacing the argument with the output. While this usually works, it doesn’t split words. The dash expansion code, which is necessary to split args before compilation, also naively splits on IFS, leading to commands like `tr “ “ “ “` being parsed as four quotation marks instead of two string arguments (since every character is a CArgChar).

I’m finishing `bash_expand.py`, which sketches out using a bash server to expand asts before compilation, like the dash code. I’ll send (another) PR to sh-expand with it (hopefully soon!).

2025-01-05 01:13 UTC, angelhof commented
> The current problem is that pash expands words in bash mode by calling `echo {arg}` for every arg, replacing the argument with the output. While this usually works, it doesn’t split words. Without a bash argument expander, currently they’re just split naively on IFS, leading to commands like `tr “ “ “ “` being parsed as four quotation marks instead of two string arguments (since every character is a CArgChar).
> 
> I’m finishing `bash_expand.py`, which already sketches out using a bash server to expand asts before compilation, like the dash code. I’ll send (another) PR to sh-expand with it (hopefully soon!).

Ohh, that is a bummer... Happy to discuss the solution if needed!

2025-01-15 03:44 UTC, BolunThompson commented
I refactored this to use the new (semi-robust) bash expansion server code in binpash/sh-expand#9. Requires #742 to make the tests work, and binpash/shasta#8 for some minor bug fixes.

The bash tests pass on my machine (the dash tests don’t, but I think that’s a problem with my local environment), although a large fraction of the bash tests are commented out. I didn’t test which of those work vs not with the new changes — I can open an issue once this is merged in.

2025-01-22 21:16 UTC, angelhof commented
@BolunThompson I think all the PR dependencies are merged! Let me know once this is ready for review and merging!

2025-01-23 06:50 UTC, BolunThompson commented
The tests all pass, so this should be ready for review.

2025-01-23 18:28 UTC, angelhof approved these changes
Looks great to me! Could we also add a sentence in README saying that if your script includes bash syntax you can use the beta `--bash` flag to support it? Also adding a few paragraphs in docs/bash.md to talk about the architecture of the solution?

2025-01-27 04:48 UTC, BolunThompson commented
I wrote some basic documentation — is this good or should I elaborate on some part?

2025-02-05 20:31 UTC, angelhof commented
Is the failing test case an expected bug? Can I help debug this somehow? If this is the only thing left let's try to clean it up and merge :)

2025-02-06 01:03 UTC, BolunThompson commented
No, unfortunately — I’ll need to look at this a bit more. I think it could
be an issue only with Ubuntu 20.04? It passes on my local Ubuntu 24.04
system.


On Wed, Feb 5, 2025 at 12:32 PM Konstantinos Kallas <
***@***.***> wrote:

> Is the failing test case an expected bug? Can I help debug this somehow?
> If this is the only thing left let's try to clean it up and merge :)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/binpash/pash/pull/737#issuecomment-2637962200>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AG232OD33VMBKVWVHSWEBYD2OJYNLAVCNFSM6AAAAABTU5QVNSVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDMMZXHE3DEMRQGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2025-02-06 01:54 UTC, angelhof commented
Hmmm, I merged the PR that updates Ubuntu to 24 to `future`. Could you make another commit to retrigger the tests on the new future? If that doesn't work we can follow up and see what is the issue.

2025-02-06 17:39 UTC, angelhof commented
I merged https://github.com/binpash/annotations/pull/22 so once we bump versions here in theory things should be OK?

2025-02-08 01:29 UTC, angelhof commented
- I pushed a new commit to `future` to fix a deprecated github action (tight-loop test failure).
- There also seems to be another syntax warning ("/home/runner/work/pash/pash/compiler/dspash/ir_helper.py:82: SyntaxWarning: invalid escape sequence '\ '")
- The hello bash output seems to be different for pash and bash:
```
Running hello-world-bash.sh...hello-world-bash:23.696
1.286
1c1
< 4176
---
> 5971257
```
It is totally unclear to me why :(

2025-02-08 03:16 UTC, BolunThompson commented
I was playing around with it, and it only occurs on Ubuntu 22.04 and before. I think it’s an expansion bug related to different bash versions? It works with “${pattern[*]}”, but not with “${pattern[@]}”. On Feb 7, 2025, at 5:30 PM, Konstantinos Kallas ***@***.***> wrote:﻿

I pushed a new commit to future to fix a deprecated github action (tight-loop test failure).
There also seems to be another syntax warning ("/home/runner/work/pash/pash/compiler/dspash/ir_helper.py:82: SyntaxWarning: invalid escape sequence '\ '")
The hello bash output seems to be different for pash and bash:

Running hello-world-bash.sh...hello-world-bash:23.696
1.286
1c1
< 4176
---
> 5971257

It is totally unclear to me why :(

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2025-02-08 03:21 UTC, BolunThompson commented
Or actually, that’s not it — I forgot that ‘*’ is an unsafe character so it just isn’t parallelized (which makes it work, of course). I’ll look at this more soon.On Feb 7, 2025, at 7:15 PM, Bolun Thompson ***@***.***> wrote:﻿I was playing around with it, and it only occurs on Ubuntu 22.04 and before. I think it’s an expansion bug related to different bash versions? It works with “${pattern[*]}”, but not with “${pattern[@]}”. On Feb 7, 2025, at 5:30 PM, Konstantinos Kallas ***@***.***> wrote:﻿

I pushed a new commit to future to fix a deprecated github action (tight-loop test failure).
There also seems to be another syntax warning ("/home/runner/work/pash/pash/compiler/dspash/ir_helper.py:82: SyntaxWarning: invalid escape sequence '\ '")
The hello bash output seems to be different for pash and bash:

Running hello-world-bash.sh...hello-world-bash:23.696
1.286
1c1
< 4176
---
> 5971257

It is totally unclear to me why :(

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2025-02-09 19:49 UTC, BolunThompson commented
This just ended up being an environment issue — I’d fixed the bug locally in binpash/sh-expand#11 and forgot to make a new release.

2025-02-09 20:34 UTC, BolunThompson commented
The posix correctness tests fail because of the old `actions/upload-artifact` version, but even after a version increment they fail because the `antikythera.csail.mit.edu` [isn’t online anymore](https://github.com/BolunThompson/pash/actions/runs/13229296576/job/36924203594?pr=5). 

(Separately, this action always succeeds because the exit code isn’t captured, so if/when the server comes back online I could add that).

2025-02-10 17:29 UTC, angelhof commented
> The posix correctness tests fail because of the old `actions/upload-artifact` version, but even after a version increment they fail because the `antikythera.csail.mit.edu` [isn’t online anymore](https://github.com/BolunThompson/pash/actions/runs/13229296576/job/36924203594?pr=5).
> 
> (Separately, this action always succeeds because the exit code isn’t captured, so if/when the server comes back online I could add that).

@BolunThompson this machine has been down for a long time, and we used to get a report to assess the results (not all tests pass, but a number of them). I don't think it will get back up soon...

2025-02-10 17:30 UTC, merged